# Generated by Django 3.0.6 on 2020-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='close_datetime',
            field=models.DateTimeField(blank=True, help_text='Optional date and time on which the form will automatically stop accepting responses. Leave blank to disable.', null=True, verbose_name='Auto-Close Date'),
        ),
    ]
