# Generated by Django 3.0.6 on 2020-05-30 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20200530_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Accepted')], default='P', help_text='Status of this response. Mark as accepted to view secrets and send submitter an acceptance email. Once marked as accepted, the status cannot be changed.', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who submitted this response. null if no account was used.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
