# Generated by Django 3.0.6 on 2020-05-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_formfield_multiple_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='formfield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
