# Generated by Django 3.0.6 on 2020-05-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200530_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='description',
            field=models.TextField(blank=True, help_text='A description that will be shown under the question in smaller text.', max_length=1024, verbose_name='Description'),
        ),
    ]
